apiVersion: v1
kind: Service
metadata:
  name: reddit-service
spec:
  type: LoadBalancer # Expose via a port on the Minikube node
  selector:
    app: reddit-app # Route traffic to Pods labeled 'app: reddit-app'
  ports:
    - protocol: TCP
      port: 8000       # Service's port within the cluster
      targetPort: 8000 # Container's port (must match containerPort in Deployment)
